internal import Institute_Linter_Rule_Architecture
internal import Institute_Linter_Rule_Byte
internal import Institute_Linter_Rule_Cardinal
internal import Institute_Linter_Rule_Closure
internal import Institute_Linter_Rule_Conformance
internal import Institute_Linter_Rule_Foundation
internal import Institute_Linter_Rule_Framework
internal import Institute_Linter_Rule_Idiom
internal import Institute_Linter_Rule_Manifest
internal import Institute_Linter_Rule_Memory
internal import Institute_Linter_Rule_Naming
internal import Institute_Linter_Rule_Platform
internal import Institute_Linter_Rule_RawValue
internal import Institute_Linter_Rule_Structure
internal import Institute_Linter_Rule_Testing
internal import Institute_Linter_Rule_Throws
internal import Institute_Linter_Rule_Try
internal import Institute_Linter_Rule_Unchecked
public import Lint
internal import Linter_Rules

extension Lint.Rule.Bundle {
    public static let institute: [Lint.Rule.Configuration] =
        Lint.Rule.Bundle.universal + [
            .enable(.`architecture import boundary`),
            .enable(.`architecture foundation type`),
            .enable(.`architecture namespace shape`),
            .enable(.`bool public parameter`),
            .enable(.`ad hoc box class`),
            .enable(.`compound identifier`),
            .enable(.`compound suite name`),
            .enable(.`compound type name`),
            .enable(.`variable named impl`),
            .enable(.`int public parameter`),
            .enable(.`namespace adoption typealias`),
            .enable(.`property named flags`),
            .enable(.`redundant prefix`),
            .enable(.`single type namespace`),
            .enable(.`tag suffix`),
            .enable(.`nested tag`),
            .enable(.`phantom suppression`),
            .enable(.`unification typealias`),
            .enable(.`diagnostic message format`),
            .enable(.`foundation import`),
            .enable(.`xctest import`),
            .enable(.`uint8 conforms to byte protocol`),
            .enable(.`byte conforms to arithmetic protocol`),
            .enable(.`binary serializable uint8 witness`),
            .enable(.`binary serializable rawvalue uint8`, severity: .error),
            .enable(.`uint8 ascii extension`),
            .enable(.`uint8 forwarder missing disfavored`),
            .enable(.`stdlib forwarder outside sli`),
            .enable(.`leaf body typealias missing`),
            .enable(.`configuration before content`),
            .enable(.`lifecycle order`),
            .enable(.`unlabeled lifecycle closure`),
            .enable(.`bounded index static capacity`),
            .enable(.`enumerated with subscript`),
            .enable(.`intermediate binding then return`),
            .enable(.`counter loop iteration`),
            .enable(.`string utf8 scanning`),
            .enable(.`sli literal`),
            .enable(.`unknown default`),
            .enable(.`bare string dependency`),
            .enable(.`path dependency`),
            .enable(.`canonical settings tail`),
            .enable(.`statement where expression fits`),
            .enable(.`existential parameter`),
            .enable(.`platform floor`),
            .enable(.`upward layer edge`),
            .enable(.`module selector spelling`),
            .enable(.`ascii identifier`),
            .enable(.`exported import`),
            .enable(.`comment in source`),
            .enable(.`fatal error outside tests`),
            .enable(.`unchecked try outside tests`),
            .enable(.`test target naming`),
            .enable(.`default trait`),
            .enable(.`package policy revision 1`, severity: .warning),
            .enable(.`manifest naming grammar`),
            .enable(.`path name grammar`),
            .enable(.`foundation integration leaf target`),
            .enable(.`borrowing self short circuit`),
            .enable(.`noncopyable error`),
            .enable(.`extension noncopyable constraint`),
            .enable(.`nonisolated unsafe without invariant`),
            .enable(.`safe attribute undocumented`),
            .enable(.`pointer advanced by`),
            .enable(.`sendable struct with class member`),
            .enable(.`unchecked sendable revalidation anchor`),
            .enable(.`unsafe assignment granularity`),
            .enable(.`sending return conditional sendable state`),
            .enable(.`c type in public api`),
            .enable(.`convention c representability`),
            .enable(.`dead case per platform`),
            .enable(.`compound platform namespace root`, severity: .error),
            .enable(.`optimize suppression attribute`),
            .enable(.`optionset shell pattern`),
            .enable(.`platform layer import`),
            .enable(.`canimport conditional`),
            .enable(.`swift protocol qualification`),
            .enable(.`system subdomain`),
            .enable(.`typealiased namespace bridge`),
            .enable(.`hoisted protocol alias`),
            .enable(.`minimal type body`),
            .enable(.`raw value access`),
            .enable(.`single type per file`),
            .enable(.`file name nested path`),
            .enable(.`extension file naming`),
            .enable(.`throwing wrapper init`),
            .enable(.`type transform placement`),
            .enable(.`wrapper backing exposed`),
            .enable(.`protocol sentinel under generic front door`),
            .enable(.`test file suffix`),
            .enable(.`test function naming`),
            .enable(.`performance suite serialized`),
            .enable(.`test display name string`),
            .enable(.`closure typed throws annotation`),
            .enable(.`do throws for typed catch`),
            .enable(.`do throws for typed catch with throw`),
            .enable(.`existential throws`),
            .enable(.`generic throws missing never`),
            .enable(.`hoisted error in public throws`),
            .enable(.`fully qualified error in typed throws`),
            .enable(.`lifecycle typealias review`),
            .enable(.`callback result over throws thunk`),
            .enable(.`result wrapper for rethrows shim`),
            .enable(.`typed throws cannot use self error`),
            .enable(.`untyped throws`),
            .enable(.`try optional`),
            .enable(.`unchecked call site`),
            .enable(.`zero or one literal`),
            .enable(.`count minus one`),
            .enable(.`bitpattern rawvalue chain`),
            .enable(.`chained rawvalue access`),
            .enable(.`tagged extension public init`),
            .enable(.`tagged unchecked with typed alternative`),
        ]
}
